"""
CoinDCX Futures Bot — Streamlit Dashboard
==========================================
Deploy to Streamlit Community Cloud for a shareable public URL.

Local run:
  streamlit run dcx_dashboard.py

The dashboard reads two JSON files updated by dcx_main.py:
  dcx_state.json    — live bot state (capital, positions, indicators)
  dcx_trades.json   — full trade history (open + closed)
  dcx_backtest.json — backtest results (generated by coindcx/backtest.py)
"""

import json
import time
import urllib.request
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd
import streamlit as st

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title  = "CoinDCX Futures Bot",
    page_icon   = "📈",
    layout      = "wide",
    initial_sidebar_state = "expanded",
)

SYMBOLS = [
    "B-ETH_USDT", "B-SOL_USDT", "B-HYPE_USDT",
    "B-AAVE_USDT", "B-ZEC_USDT", "B-UNI_USDT",
]

REFRESH_INTERVAL = 30   # seconds


# ── Data loading helpers ──────────────────────────────────────────────────────

def _load_json(path: str) -> Optional[Dict]:
    p = Path(path)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def _fetch_gist(url: str) -> Optional[Dict]:
    """Fetch JSON from a raw Gist URL (used on Streamlit Cloud)."""
    try:
        with urllib.request.urlopen(url, timeout=5) as r:
            return json.loads(r.read())
    except Exception:
        return None


def _load_or_fetch(path: str, secret_key: str) -> Optional[Dict]:
    """Read from Gist URL (Streamlit Cloud) or fall back to local file (VPS/dev)."""
    try:
        url = st.secrets[secret_key]
        data = _fetch_gist(url)
        if data is not None:
            return data
    except (KeyError, AttributeError):
        pass
    return _load_json(path)


@st.cache_data(ttl=REFRESH_INTERVAL)
def load_state() -> Optional[Dict]:
    return _load_or_fetch("dcx_state.json", "GIST_STATE_URL")


@st.cache_data(ttl=REFRESH_INTERVAL)
def load_trades() -> Optional[Dict]:
    return _load_or_fetch("dcx_trades.json", "GIST_TRADES_URL")


@st.cache_data(ttl=300)
def load_backtest() -> Optional[Dict]:
    return _load_json("dcx_backtest.json")   # always from repo, never Gist


# ── Sidebar ───────────────────────────────────────────────────────────────────

st.sidebar.title("CoinDCX Futures Bot")
st.sidebar.markdown("---")

state = load_state()
if state:
    mode_label = "📝 PAPER" if state.get("paper") else "🔴 LIVE"
    paused_label = "⏸ PAUSED" if state.get("paused") else "▶️ ACTIVE"
    st.sidebar.markdown(f"**Mode:** {mode_label}")
    st.sidebar.markdown(f"**State:** {paused_label}")
    last_update = state.get("timestamp", 0)
    st.sidebar.markdown(
        f"**Last update:** {time.strftime('%H:%M:%S UTC', time.gmtime(last_update))}"
    )
else:
    st.sidebar.info("🔌 Bot offline — backtest data only")

page = st.sidebar.radio(
    "View",
    ["Live Overview", "Trade History", "Backtest Results", "Symbol Detail"],
)
st.sidebar.markdown("---")
st.sidebar.caption("Auto-refreshes every 30 s. Press R to reload manually.")

# ── Helper renderers ──────────────────────────────────────────────────────────

def _colour(val: float) -> str:
    return "green" if val >= 0 else "red"


def _pct(val: float) -> str:
    return f"{val:+.2f}%"


def _usdt(val: float) -> str:
    sign = "+" if val >= 0 else ""
    return f"{sign}{val:.4f} USDT"


# ══════════════════════════════════════════════════════════════════════════════
# PAGE 1 — Live Overview
# ══════════════════════════════════════════════════════════════════════════════

if page == "Live Overview":
    st.title("📈 Live Overview")

    if not state:
        st.info(
            "Bot is offline — no live data available. "
            "Run `python dcx_main.py` on your VPS to see live stats here. "
            "Use the **Backtest Results** page to view strategy performance."
        )
        st.stop()

    # ── KPI row ───────────────────────────────────────────────────────────────
    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Capital",     f"${state['capital']:.2f}",      f"{state['total_return_pct']:+.2f}%")
    col2.metric("Total P&L",   _usdt(state['total_pnl']))
    col3.metric("Win Rate",    f"{state['win_rate']:.0%}",       f"{state['wins']}W / {state['losses']}L")
    col4.metric("Open Positions", state['open_count'])
    col5.metric("Total Trades",   state['total_trades'])

    st.markdown("---")

    # ── Open Positions ────────────────────────────────────────────────────────
    st.subheader("Open Positions")
    open_pos = state.get("open_positions", [])
    if open_pos:
        df_open = pd.DataFrame(open_pos)[[
            "symbol", "direction", "entry_price", "stop_loss", "take_profit",
            "quantity", "margin", "leverage",
        ]]
        df_open["opened_at"] = pd.to_datetime(
            [p["opened_at"] for p in open_pos], unit="s", utc=True
        ).strftime("%Y-%m-%d %H:%M UTC")
        st.dataframe(df_open, use_container_width=True)
    else:
        st.info("No open positions.")

    # ── Indicators ────────────────────────────────────────────────────────────
    st.subheader("Market Indicators (4H)")
    indicators = state.get("indicators", {})
    if indicators:
        rows = []
        for sym, ind in indicators.items():
            if not ind or ind.get("ema", 0) == 0:
                continue
            bias = "🟢 ABOVE EMA (Bullish)" if ind["side"] == "ABOVE" else "🔴 BELOW EMA (Bearish)"
            rows.append({
                "Symbol": sym,
                "Price":  round(ind.get("close", 0), 4),
                "EMA 50": round(ind.get("ema", 0), 4),
                "ATR":    round(ind.get("atr", 0), 4),
                "Bias":   bias,
            })
        if rows:
            st.dataframe(pd.DataFrame(rows), use_container_width=True)

    # ── Equity curve from closed trades ──────────────────────────────────────
    trades_data = load_trades()
    if trades_data:
        closed = trades_data.get("closed", [])
        if closed:
            df_eq = pd.DataFrame(closed)
            if "closed_at" in df_eq.columns and "pnl" in df_eq.columns:
                df_eq = df_eq.dropna(subset=["closed_at", "pnl"]).sort_values("closed_at")
                initial = trades_data.get("capital", 1000) - df_eq["pnl"].sum()
                df_eq["equity"] = initial + df_eq["pnl"].cumsum()
                df_eq["closed_at"] = pd.to_datetime(df_eq["closed_at"], unit="s", utc=True)
                st.subheader("Equity Curve")
                st.line_chart(df_eq.set_index("closed_at")["equity"])


# ══════════════════════════════════════════════════════════════════════════════
# PAGE 2 — Trade History
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Trade History":
    st.title("📋 Trade History")

    trades_data = load_trades()
    if not trades_data:
        st.error("No trades file found.")
        st.stop()

    closed = trades_data.get("closed", [])
    if not closed:
        st.info("No closed trades yet.")
        st.stop()

    df = pd.DataFrame(closed)
    df["opened_at"]  = pd.to_datetime(df["opened_at"],  unit="s", utc=True)
    df["closed_at"]  = pd.to_datetime(df["closed_at"],  unit="s", utc=True)
    df["pnl_str"]    = df["pnl"].apply(_usdt)
    df["duration_h"] = ((df["closed_at"] - df["opened_at"]).dt.total_seconds() / 3600).round(1)

    # Filters
    col_f1, col_f2 = st.columns(2)
    sym_filter = col_f1.multiselect(
        "Symbol", sorted(df["symbol"].unique()), default=sorted(df["symbol"].unique())
    )
    dir_filter = col_f2.multiselect(
        "Direction", ["LONG", "SHORT"], default=["LONG", "SHORT"]
    )
    df_f = df[df["symbol"].isin(sym_filter) & df["direction"].isin(dir_filter)]

    # Per-symbol stats
    st.subheader("Per-Symbol Performance")
    grp = df_f.groupby("symbol").agg(
        Trades=("pnl", "count"),
        Wins=("pnl", lambda x: (x > 0).sum()),
        Losses=("pnl", lambda x: (x <= 0).sum()),
        WinRate=("pnl", lambda x: (x > 0).mean()),
        TotalPnL=("pnl", "sum"),
        AvgPnL=("pnl", "mean"),
    ).reset_index()
    grp["WinRate"] = grp["WinRate"].apply(lambda v: f"{v:.0%}")
    grp["TotalPnL"] = grp["TotalPnL"].round(4)
    grp["AvgPnL"] = grp["AvgPnL"].round(4)
    st.dataframe(grp, use_container_width=True)

    # Full table
    st.subheader("All Closed Trades")
    display_cols = [
        "symbol", "direction", "entry_price", "exit_price",
        "exit_reason", "pnl", "duration_h", "opened_at",
    ]
    st.dataframe(df_f[display_cols].sort_values("opened_at", ascending=False), use_container_width=True)

    # P&L by symbol bar chart
    st.subheader("P&L by Symbol")
    pnl_sym = df_f.groupby("symbol")["pnl"].sum().reset_index()
    st.bar_chart(pnl_sym.set_index("symbol"))


# ══════════════════════════════════════════════════════════════════════════════
# PAGE 3 — Backtest Results
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Backtest Results":
    st.title("🔬 Backtest Results")
    st.caption(
        "Run `python -m coindcx.backtest` to generate results using real CoinDCX/Binance data."
    )

    bt = load_backtest()
    if not bt:
        st.warning("No backtest file found. Run the backtest first.")
        st.stop()

    # Summary table
    rows = []
    for sym, data in bt.items():
        s = data["summary"]
        rows.append({
            "Symbol":       sym,
            "Trades":       s["total_trades"],
            "Wins":         s["wins"],
            "Losses":       s["losses"],
            "Win Rate":     f"{s['win_rate']:.0%}",
            "Total P&L":    round(s["total_net_pnl"], 4),
            "Return %":     f"{s['total_return_pct']:+.2f}%",
            "Max Drawdown": f"{s['max_drawdown']:.1f}%",
        })
    st.subheader("Strategy Summary")
    st.dataframe(pd.DataFrame(rows), use_container_width=True)

    # Per-symbol equity curve
    sym_choice = st.selectbox("View equity curve for:", sorted(bt.keys()))
    if sym_choice in bt:
        eq = bt[sym_choice]["equity_curve"]
        st.subheader(f"Equity Curve — {sym_choice}")
        st.line_chart(pd.Series(eq, name="Equity (USDT)"))

        # Trade table for selected symbol
        trades_bt = bt[sym_choice].get("trades", [])
        if trades_bt:
            df_bt = pd.DataFrame(trades_bt)
            df_bt["entry_ts"] = pd.to_datetime(df_bt["entry_bar_ts"], unit="ms", utc=True)
            df_bt["exit_ts"]  = pd.to_datetime(df_bt["exit_bar_ts"],  unit="ms", utc=True)
            st.subheader(f"Trades — {sym_choice}")
            display_bt = [
                "direction", "entry_price", "exit_price", "exit_reason",
                "net_pnl", "fee", "entry_ts", "exit_ts",
            ]
            st.dataframe(df_bt[display_bt], use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# PAGE 4 — Symbol Detail
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Symbol Detail":
    st.title("🔍 Symbol Detail")

    sym = st.selectbox("Symbol", SYMBOLS)
    trades_data = load_trades()

    if not trades_data:
        st.error("No trades file found.")
        st.stop()

    closed = trades_data.get("closed", [])
    df_all = pd.DataFrame(closed) if closed else pd.DataFrame()

    if df_all.empty or sym not in df_all.get("symbol", pd.Series()).values:
        st.info(f"No closed trades for {sym} yet.")
    else:
        df_s = df_all[df_all["symbol"] == sym].copy()
        df_s["opened_at"] = pd.to_datetime(df_s["opened_at"], unit="s", utc=True)
        df_s["closed_at"] = pd.to_datetime(df_s["closed_at"], unit="s", utc=True)

        wins   = (df_s["pnl"] > 0).sum()
        losses = (df_s["pnl"] <= 0).sum()
        total_pnl = df_s["pnl"].sum()

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Trades",   len(df_s))
        col2.metric("Win Rate", f"{wins / len(df_s):.0%}")
        col3.metric("Total P&L", f"{total_pnl:+.4f}")
        col4.metric("W / L",    f"{wins} / {losses}")

        st.subheader("Equity Curve")
        df_s_sorted = df_s.sort_values("closed_at")
        initial_eq  = trades_data.get("capital", 1000) - df_s_sorted["pnl"].sum()
        df_s_sorted["equity"] = initial_eq + df_s_sorted["pnl"].cumsum()
        st.line_chart(df_s_sorted.set_index("closed_at")["equity"])

        st.subheader("Win/Loss by Exit Reason")
        reason_grp = df_s.groupby("exit_reason")["pnl"].agg(["count", "sum"]).reset_index()
        reason_grp.columns = ["Exit Reason", "Count", "Total P&L"]
        st.dataframe(reason_grp, use_container_width=True)

        st.subheader("All Trades")
        st.dataframe(
            df_s[["direction", "entry_price", "exit_price", "exit_reason", "pnl", "opened_at"]],
            use_container_width=True,
        )

    # Indicators from state
    if state:
        ind = state.get("indicators", {}).get(sym, {})
        if ind and ind.get("ema", 0) > 0:
            st.subheader("Current Indicators")
            st.json(ind)

# ── Auto-refresh ──────────────────────────────────────────────────────────────

st.markdown("---")
st.caption(f"Dashboard refreshes automatically. Data lag ≤ {REFRESH_INTERVAL}s from bot.")
